Create changeTheme.php
rerang/Palette-Diary pull request #17
Opened 2022-05-14 14:24 UTC by kmonasu

테마변경

2022-05-14 15:36 UTC, rerang requested changes

2022-05-14 15:36 UTC, rerang commented on public/src/changeTheme.php
> +$email = $json['email'];
헤더에서 가져오셔야 합니다.

2022-05-14 15:36 UTC, rerang commented on public/src/changeTheme.php
> +$updateSql = "update user set theme_code='$themeCode' where email='$email';";
$themeCode 변수는 없는 것 같습니다.

2022-05-14 15:36 UTC, rerang commented on public/src/changeTheme.php
> +$themeCodeSql = "select * from theme where theme_code='$userThemeCode';";
왜 주시는 내용일까요

2022-05-15 09:16 UTC, kmonasu commented on public/src/changeTheme.php
> +$themeCodeSql = "select * from theme where theme_code='$userThemeCode';";
필요하실것같아서 바뀐테마드렸습니다 필요없으면 삭제할까요?

2022-05-15 11:44 UTC, kmonasu commented on public/src/changeTheme.php
> +$themeCodeSql = "select * from theme where theme_code='$userThemeCode';";
업데이트 후 벡그라운드 픽의 소스드려야 되는거 아닌요? 안드려도 되나요 ? 삭제할까요..?

2022-05-15 14:43 UTC, closed without merging