Create deleteDiary
rerang/Palette-Diary pull request #49
Opened 2022-05-19 18:03 UTC by chfhd5501

일기를 삭제하면 참조하고 있는 해피 다이어리에 오류가 발생해서 일단 삭제할 수 없다고 해놨습니당
이 부분 얘기 나눠봐야 할 것 같아요

2022-05-21 15:23 UTC, rerang commented
삭제하게되면 해피저금통에 다이어리코드를 먼저 삭제해주시면 될 것 같아요

2022-05-22 13:32 UTC, rerang commented on public/src/Diary/deleteDiary
> +    $selectHappyDiarySql = "select * from happy_diary where email='$email' and diary_code='$deleteDiaryCode';";
diary code 가 primary key이므로 해피다이어리에서 해당 다이어리 코드를 참조하고 있는지 확인하기 위해서는 diary code만 확인해주시면 될 것 같습니다.

2022-05-22 13:32 UTC, rerang commented on public/src/Diary/deleteDiary
> +        $deleteDiarySql = "delete from diary where email='$email' and diary_code='$deleteDiaryCode';";
diary code 가 primary key이므로 삭제시 diary code만 확인해주시면 될 것 같습니다.

2022-05-22 13:32 UTC, rerang commented on public/src/Diary/deleteDiary
> +        if(!$deleteDiaryDetailResult || !$deleteDiaryResult){
만약 32번 행에서 지워진 상태가 아니라면, 36번에서 오류가 생길 것이기 때문에 따로 확인을 해주셔야 할 것 같습니다.

2022-05-22 13:39 UTC, chfhd5501 commented on public/src/Diary/deleteDiary
> +        $deleteDiarySql = "delete from diary where email='$email' and diary_code='$deleteDiaryCode';";
저희 다이어리 코드가 순차코드로 들어가는데 email 확인을 빼버리면 sql문 실행했을 때 해당 유저의 일기뿐만 아니라 다른 사람들의 일기까지 삭제되지 않을까요??

2022-05-22 13:53 UTC, chfhd5501 commented on public/src/Diary/deleteDiary
> +    $selectHappyDiarySql = "select * from happy_diary where email='$email' and diary_code='$deleteDiaryCode';";
업데이트한 거 한번 확인해주세요!

2022-05-22 14:04 UTC, rerang requested changes

2022-05-22 14:04 UTC, rerang commented on public/src/Diary/deleteDiary
> +    if($selectHappyDiaryResult) { // 해피 다이어리에서 참조하고 있는 다이어리 코드가 있다면
이전 코드에서 throw exception만 따로 주시면 좋을 것 같아요

2022-06-03 00:34 UTC, rerang approved these changes

2022-06-03 00:34 UTC, merged