Create  statistics.php
rerang/Palette-Diary pull request #67
Opened 2022-05-29 11:12 UTC by kmonasu

이번주 color와 keyword를 배열형태로 가져왔습니다. date("w")는 요일을 0~6으로 0:일요일 ~ 6:토요일 으로 나오는 함수임
strtotime으로 현재시간기준으로 달월을 가져와서 DB와 비교후 가져옴

2022-05-29 11:19 UTC, kmonasu commented
이번주 통계입니다

2022-05-29 11:34 UTC, rerang requested changes

2022-05-29 11:34 UTC, rerang commented on public/src/statistics/statisticsWeek.php
> +    $checkingDiaryExistSql="select * from diary where email='$email'";
기간 내에 존재하는지 확인해야할 것 같습니다

2022-05-29 11:36 UTC, rerang requested changes

2022-05-29 11:36 UTC, rerang commented on public/src/statistics/statisticsWeek.php
> +            $checkSqlWeek = "select color,keyword from happy_diary left join diary on happy_diary.email='$email' where (substr(diary.d_date,6,5)='$sunday' or substr(diary.d_date,6,5)='$monday' or
해피다이어리와 조이하는 이유가 있나요

2022-05-30 01:10 UTC, kmonasu commented on public/src/statistics/statisticsWeek.php
> +            $checkSqlWeek = "select color,keyword from happy_diary left join diary on happy_diary.email='$email' where (substr(diary.d_date,6,5)='$sunday' or substr(diary.d_date,6,5)='$monday' or
join을 안써도 and로 해도 되지 너무 보기 복잡해서 join을 사용하여 on과 where로 조건을 나누었습니다 쓸데없긴한데 보기는 편할것같아서요 join빼라고하셔도 상관없습니다

2022-05-31 18:48 UTC, closed without merging